version: '3'
services:
  redis:
    image: redis:alpine
    restart: always
    entrypoint: redis-server --save "" --appendonly no

  fake-data-generator:
    restart: always
    image: fake-data-generator
    build: ./fake_data_generator/
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  backend:
    image: data-visualisation-backend
    build: ./backend/
    environment:
      - REDIS_HOST=redis
    restart: always
    ports:
      - "127.0.0.1:8080:80"
